spring.application.name=api-gateway-service
server.port=8084

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Product Service
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**

# Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**