
services:
  app:
    build: .
    container_name: student-app
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rishi
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: student
    ports:
      - "3307:3306"
    networks:
      - my-network
    volumes:
      - mysql-my-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  my-network:
    driver: bridge

volumes:
  mysql-my-data:
