spring.application.name=StudentDocker

server.port=8090


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://mysql:3306/student
spring.datasource.username = rishi
spring.datasource.password = 1234
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true